use crate::x86_instr_arg_type::X86ArgType::{AX, NONE};
use crate::x86_instr_operand::Operand;

pub const instructions_fpu_single: [Operand;36] = [
    Operand::new(0xD9, 0xD0, 0, "fnop", NONE, NONE, 0),
    Operand::new(0xD9, 0xE0, 0, "fchs", NONE, NONE, 0),
    Operand::new(0xD9, 0xE1, 0, "fabs", NONE, NONE, 0),
    Operand::new(0xD9, 0xE4, 0, "ftst", NONE, NONE, 0),
    Operand::new(0xD9, 0xE5, 0, "fxam", NONE, NONE, 0),
    Operand::new(0xD9, 0xE8, 0, "fld1", NONE, NONE, 0),
    Operand::new(0xD9, 0xE9, 0, "fldl2t", NONE, NONE, 0),
    Operand::new(0xD9, 0xEA, 0, "fldl2e", NONE, NONE, 0),
    Operand::new(0xD9, 0xEB, 0, "fldpi", NONE, NONE, 0),
    Operand::new(0xD9, 0xEC, 0, "fldlg2", NONE, NONE, 0),
    Operand::new(0xD9, 0xED, 0, "fldln2", NONE, NONE, 0),
    Operand::new(0xD9, 0xEE, 0, "fldz", NONE, NONE, 0),
    Operand::new(0xD9, 0xF0, 0, "f2xm1", NONE, NONE, 0),
    Operand::new(0xD9, 0xF1, 0, "fyl2x", NONE, NONE, 0),
    Operand::new(0xD9, 0xF2, 0, "fptan", NONE, NONE, 0),
    Operand::new(0xD9, 0xF3, 0, "fpatan", NONE, NONE, 0),
    Operand::new(0xD9, 0xF4, 0, "fxtract", NONE, NONE, 0),
    Operand::new(0xD9, 0xF5, 0, "fprem1", NONE, NONE, 0),
    Operand::new(0xD9, 0xF6, 0, "fdecstp", NONE, NONE, 0),
    Operand::new(0xD9, 0xF7, 0, "fincstp", NONE, NONE, 0),
    Operand::new(0xD9, 0xF8, 0, "fprem", NONE, NONE, 0),
    Operand::new(0xD9, 0xF9, 0, "fyl2xp1", NONE, NONE, 0),
    Operand::new(0xD9, 0xFA, 0, "fsqrt", NONE, NONE, 0),
    Operand::new(0xD9, 0xFB, 0, "fsincos", NONE, NONE, 0),
    Operand::new(0xD9, 0xFC, 0, "frndint", NONE, NONE, 0),
    Operand::new(0xD9, 0xFD, 0, "fscale", NONE, NONE, 0),
    Operand::new(0xD9, 0xFE, 0, "fsin", NONE, NONE, 0),
    Operand::new(0xD9, 0xFF, 0, "fcos", NONE, NONE, 0),
    Operand::new(0xDA, 0xE9, 0, "fucompp", NONE, NONE, 0),
    Operand::new(0xDB, 0xE0, 0, "fneni", NONE, NONE, 0),
    Operand::new(0xDB, 0xE1, 0, "fndisi", NONE, NONE, 0),
    Operand::new(0xDB, 0xE2, 0, "fnclex", NONE, NONE, 0),
    Operand::new(0xDB, 0xE3, 0, "fninit", NONE, NONE, 0),
    Operand::new(0xDB, 0xE4, 0, "fnsetpm", NONE, NONE, 0),
    Operand::new(0xDE, 0xD9, 0, "fcompp", NONE, NONE, 0),
    Operand::new(0xDF, 0xE0, 0, "fnstsw", AX, NONE, 0),
];
