use crate::x86_instr_def::OP_ARG2_IMM8;
use crate::x86_instr_arg_type::X86ArgType::{IMM8, MEM, MM, MMX, MMXONLY, NONE, REG, REGONLY, RM, XM, XMM};
use crate::x86_instr_operand::Operand;

pub const INSTRUCTIONS_SSE: [Operand;109] = [
    Operand::new(0x10, 8,  0, "movups",     XMM,    XM, 0),
    Operand::new(0x11, 8,  0, "movups",     XM,     XMM, 0),
    Operand::new(0x12, 8,  0, "movlps",     XMM,    XM, 0),    /* fixme: movhlps */
    Operand::new(0x13, 8,  0, "movlps",     MEM,    XMM, 0),
    Operand::new(0x14, 8,  0, "unpcklps",   XMM,    XM, 0),
    Operand::new(0x15, 8,  0, "unpckhps",   XMM,    XM, 0),
    Operand::new(0x16, 8,  0, "movhps",     XMM,    XM, 0),    /* fixme: movlhps */
    Operand::new(0x17, 8,  0, "movhps",     MEM,    XMM, 0),
    Operand::new(0x28, 8,  0, "movaps",     XMM,    XM, 0),
    Operand::new(0x29, 8,  0, "movaps",     XM,     XMM, 0),
    Operand::new(0x2A, 8,  0, "cvtpi2ps",   XMM,    MM, 0),
    Operand::new(0x2B, 8,  0, "movntps",    MEM,    XMM, 0),
    Operand::new(0x2C, 8,  0, "cvttps2pi",  MMX,    XM, 0),
    Operand::new(0x2D, 8,  0, "cvtps2pi",   MMX,    XM, 0),
    Operand::new(0x2E, 8,  0, "ucomiss",    XMM,    XM, 0),
    Operand::new(0x2F, 8,  0, "comiss",     XMM,    XM, 0),

    Operand::new(0x50, 8,  0, "movmskps",   REGONLY,XMM, 0),
    Operand::new(0x51, 8,  0, "sqrtps",     XMM,    XM, 0),
    Operand::new(0x52, 8,  0, "rsqrtps",    XMM,    XM, 0),
    Operand::new(0x53, 8,  0, "rcpps",      XMM,    XM, 0),
    Operand::new(0x54, 8,  0, "andps",      XMM,    XM, 0),
    Operand::new(0x55, 8,  0, "andnps",     XMM,    XM, 0),
    Operand::new(0x56, 8,  0, "orps",       XMM,    XM, 0),
    Operand::new(0x57, 8,  0, "xorps",      XMM,    XM, 0),
    Operand::new(0x58, 8,  0, "addps",      XMM,    XM, 0),
    Operand::new(0x59, 8,  0, "mulps",      XMM,    XM, 0),
    Operand::new(0x5A, 8,  0, "cvtps2pd",   XMM,    XM, 0),
    Operand::new(0x5B, 8,  0, "cvtdq2ps",   XMM,    XM, 0),
    Operand::new(0x5C, 8,  0, "subps",      XMM,    XM, 0),
    Operand::new(0x5D, 8,  0, "minps",      XMM,    XM, 0),
    Operand::new(0x5E, 8,  0, "divps",      XMM,    XM, 0),
    Operand::new(0x5F, 8,  0, "maxps",      XMM,    XM, 0),
    Operand::new(0x60, 8,  0, "punpcklbw",  MMX,    MM, 0),
    Operand::new(0x61, 8,  0, "punpcklwd",  MMX,    MM, 0),
    Operand::new(0x62, 8,  0, "punpckldq",  MMX,    MM, 0),
    Operand::new(0x63, 8,  0, "packsswb",   MMX,    MM, 0),
    Operand::new(0x64, 8,  0, "pcmpgtb",    MMX,    MM, 0),
    Operand::new(0x65, 8,  0, "pcmpgtw",    MMX,    MM, 0),
    Operand::new(0x66, 8,  0, "pcmpgtd",    MMX,    MM, 0),
    Operand::new(0x67, 8,  0, "packuswb",   MMX,    MM, 0),
    Operand::new(0x68, 8,  0, "punpckhbw",  MMX,    MM, 0),
    Operand::new(0x69, 8,  0, "punpckhwd",  MMX,    MM, 0),
    Operand::new(0x6A, 8,  0, "punpckhdq",  MMX,    MM, 0),
    Operand::new(0x6B, 8,  0, "packssdw",   MMX,    MM, 0),
    /* 6C/D unused */
    Operand::new(0x6E, 8,  0, "movd",       MMX,    RM, 0),
    Operand::new(0x6F, 8,  0, "movq",       MMX,    MM, 0),
    Operand::new(0x70, 8,  0, "pshufw",     MMX,    MM,     OP_ARG2_IMM8),
    Operand::new(0x71, 2,  0, "psrlw",      MMXONLY,IMM8, 0),  /* fixme: make sure this works */
    Operand::new(0x71, 4,  0, "psraw",      MMXONLY,IMM8, 0),
    Operand::new(0x71, 6,  0, "psllw",      MMXONLY,IMM8, 0),
    Operand::new(0x72, 2,  0, "psrld",      MMXONLY,IMM8, 0),
    Operand::new(0x72, 4,  0, "psrad",      MMXONLY,IMM8, 0),
    Operand::new(0x72, 6,  0, "pslld",      MMXONLY,IMM8, 0),
    Operand::new(0x73, 2,  0, "psrlq",      MMXONLY,IMM8, 0),
    Operand::new(0x73, 6,  0, "psllq",      MMXONLY,IMM8, 0),
    Operand::new(0x74, 8,  0, "pcmpeqb",    MMX,    MM, 0),
    Operand::new(0x75, 8,  0, "pcmpeqw",    MMX,    MM, 0),
    Operand::new(0x76, 8,  0, "pcmpeqd",    MMX,    MM, 0),
    Operand::new(0x77, 8,  0, "emms", NONE, NONE, 0),
    Operand::new(0x7E, 8,  0, "movd",       RM,     MMX, 0),
    Operand::new(0x7F, 8,  0, "movq",       MM,     MMX, 0),
    Operand::new(0xC2, 8,  0, "cmpps",      XMM,    XM,     OP_ARG2_IMM8),
    Operand::new(0xC3, 8,  0, "movnti",     MEM,    REG, 0),
    Operand::new(0xC4, 8,  0, "pinsrw",     MMX,    RM,     OP_ARG2_IMM8),
    Operand::new(0xC5, 8,  0, "pextrw",     REGONLY,MMX,    OP_ARG2_IMM8),
    Operand::new(0xC6, 8,  0, "shufps",     XMM,    XM,     OP_ARG2_IMM8),
    Operand::new(0xD1, 8,  0, "psrlw",      MMX,    MM, 0),
    Operand::new(0xD2, 8,  0, "psrld",      MMX,    MM, 0),
    Operand::new(0xD3, 8,  0, "psrlq",      MMX,    MM, 0),
    Operand::new(0xD4, 8,  0, "paddq",      MMX,    MM, 0),
    Operand::new(0xD5, 8,  0, "pmullw",     MMX,    MM, 0),
    /* D6 unused */
    Operand::new(0xD7, 8,  0, "pmovmskb",   REGONLY,MMX, 0),
    Operand::new(0xD8, 8,  0, "psubusb",    MMX,    MM, 0),
    Operand::new(0xD9, 8,  0, "psubusw",    MMX,    MM, 0),
    Operand::new(0xDA, 8,  0, "pminub",     MMX,    MM, 0),
    Operand::new(0xDB, 8,  0, "pand",       MMX,    MM, 0),
    Operand::new(0xDC, 8,  0, "paddusb",    MMX,    MM, 0),
    Operand::new(0xDD, 8,  0, "paddusw",    MMX,    MM, 0),
    Operand::new(0xDE, 8,  0, "pmaxub",     MMX,    MM, 0),
    Operand::new(0xDF, 8,  0, "pandn",      MMX,    MM, 0),
    Operand::new(0xE0, 8,  0, "pavgb",      MMX,    MM, 0),
    Operand::new(0xE1, 8,  0, "psraw",      MMX,    MM, 0),
    Operand::new(0xE2, 8,  0, "psrad",      MMX,    MM, 0),
    Operand::new(0xE3, 8,  0, "pavgw",      MMX,    MM, 0),
    Operand::new(0xE4, 8,  0, "pmulhuw",    MMX,    MM, 0),
    Operand::new(0xE5, 8,  0, "pmulhw",     MMX,    MM, 0),
    /* E6 unused */
    Operand::new(0xE7, 8,  0, "movntq",     MEM,    MMX, 0),
    Operand::new(0xE8, 8,  0, "psubsb",     MMX,    MM, 0),
    Operand::new(0xE9, 8,  0, "psubsw",     MMX,    MM, 0),
    Operand::new(0xEA, 8,  0, "pminsw",     MMX,    MM, 0),
    Operand::new(0xEB, 8,  0, "por",        MMX,    MM, 0),
    Operand::new(0xEC, 8,  0, "paddsb",     MMX,    MM, 0),
    Operand::new(0xED, 8,  0, "paddsw",     MMX,    MM, 0),
    Operand::new(0xEE, 8,  0, "pmaxsw",     MMX,    MM, 0),
    Operand::new(0xEF, 8,  0, "pxor",       MMX,    MM, 0),
    /* F0 unused */
    Operand::new(0xF1, 8,  0, "psllw",      MMX,    MM, 0),
    Operand::new(0xF2, 8,  0, "pslld",      MMX,    MM, 0),
    Operand::new(0xF3, 8,  0, "psllq",      MMX,    MM, 0),
    Operand::new(0xF4, 8,  0, "pmuludq",    MMX,    MM, 0),
    Operand::new(0xF5, 8,  0, "pmaddwd",    MMX,    MM, 0),
    Operand::new(0xF6, 8,  0, "psadbw",     MMX,    MM, 0),
    Operand::new(0xF7, 8,  0, "maskmovq",   MMX,    MMXONLY, 0),
    Operand::new(0xF8, 8,  0, "psubb",      MMX,    MM, 0),
    Operand::new(0xF9, 8,  0, "psubw",      MMX,    MM, 0),
    Operand::new(0xFA, 8,  0, "psubd",      MMX,    MM, 0),
    Operand::new(0xFB, 8,  0, "psubq",      MMX,    MM, 0),
    Operand::new(0xFC, 8,  0, "paddb",      MMX,    MM, 0),
    Operand::new(0xFD, 8,  0, "paddw",      MMX,    MM, 0),
    Operand::new(0xFE, 8,  0, "paddd",      MMX,    MM, 0),
];
